// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auaphdkzcqveepndxfwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1YXBoZGt6Y3F2ZWVwbmR4ZndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjk3ODEsImV4cCI6MjA3Mzc0NTc4MX0.67Ot1q8kPPPgvjWPiOJvnwRyhkfK2AsYn0Rz_40ynEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});